using System.Text.Json;
using System.Text.Json.Serialization;
using LlamaCloud.Exceptions;
using System = System;

namespace LlamaCloud.Models.Parsing;

/// <summary>
/// Enum for supported file extensions.
/// </summary>
[JsonConverter(typeof(LlamaParseSupportedFileExtensionsConverter))]
public enum LlamaParseSupportedFileExtensions
{
    Abw,
    Awt,
    Azw,
    Azw3,
    Azw4,
    Bmp,
    Cb7,
    Cbc,
    Cbr,
    Cbz,
    Cgm,
    Chm,
    Csv,
    Cwk,
    Dbf,
    Dif,
    Djvu,
    Doc,
    Docm,
    Docx,
    Dot,
    Dotm,
    Dotx,
    Epub,
    Et,
    Eth,
    Fb2,
    Fbz,
    Fodg,
    Fodp,
    Fods,
    Fodt,
    Fopd,
    Gif,
    Heic,
    Heif,
    Htm,
    Html,
    Htmlz,
    Hwp,
    Jpeg,
    Jpg,
    Key,
    Lit,
    Lrf,
    Lwp,
    M4a,
    Mcw,
    Md,
    Mobi,
    Mp3,
    Mp4,
    Mpeg,
    Mpga,
    Mw,
    Mwd,
    Numbers,
    Odf,
    Odg,
    Odp,
    Ods,
    Odt,
    Otg,
    Otp,
    Ots,
    Ott,
    Pages,
    Pbd,
    Pdb,
    Pdf,
    Pml,
    Png,
    Pot,
    Potm,
    Potx,
    Ppt,
    Pptm,
    Pptx,
    Prc,
    Prn,
    Psw,
    Qpw,
    Rb,
    Rtf,
    Sda,
    Sdd,
    Sdp,
    Sdw,
    Sgl,
    Slk,
    Snb,
    Stc,
    Std,
    Sti,
    Stw,
    Svg,
    Sxc,
    Sxd,
    Sxg,
    Sxi,
    Sxm,
    Sxw,
    Sylk,
    Tcr,
    Tif,
    Tiff,
    Tsv,
    Txtz,
    Uof,
    Uop,
    Uos,
    Uos1,
    Uos2,
    Uot,
    Vdx,
    Vor,
    Vsd,
    Vsdm,
    Vsdx,
    Wav,
    Wb1,
    Wb2,
    Wb3,
    Webm,
    Webp,
    Wk1,
    Wk2,
    Wk3,
    Wk4,
    Wks,
    Wn,
    Wpd,
    Wps,
    Wpt,
    Wq1,
    Wq2,
    Wri,
    Xhtm,
    Xlr,
    Xls,
    Xlsb,
    Xlsm,
    Xlsx,
    Xlw,
    Xml,
    Yxmd,
    Zabw,
}

sealed class LlamaParseSupportedFileExtensionsConverter
    : JsonConverter<LlamaParseSupportedFileExtensions>
{
    public override LlamaParseSupportedFileExtensions Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            ".abw" => LlamaParseSupportedFileExtensions.Abw,
            ".awt" => LlamaParseSupportedFileExtensions.Awt,
            ".azw" => LlamaParseSupportedFileExtensions.Azw,
            ".azw3" => LlamaParseSupportedFileExtensions.Azw3,
            ".azw4" => LlamaParseSupportedFileExtensions.Azw4,
            ".bmp" => LlamaParseSupportedFileExtensions.Bmp,
            ".cb7" => LlamaParseSupportedFileExtensions.Cb7,
            ".cbc" => LlamaParseSupportedFileExtensions.Cbc,
            ".cbr" => LlamaParseSupportedFileExtensions.Cbr,
            ".cbz" => LlamaParseSupportedFileExtensions.Cbz,
            ".cgm" => LlamaParseSupportedFileExtensions.Cgm,
            ".chm" => LlamaParseSupportedFileExtensions.Chm,
            ".csv" => LlamaParseSupportedFileExtensions.Csv,
            ".cwk" => LlamaParseSupportedFileExtensions.Cwk,
            ".dbf" => LlamaParseSupportedFileExtensions.Dbf,
            ".dif" => LlamaParseSupportedFileExtensions.Dif,
            ".djvu" => LlamaParseSupportedFileExtensions.Djvu,
            ".doc" => LlamaParseSupportedFileExtensions.Doc,
            ".docm" => LlamaParseSupportedFileExtensions.Docm,
            ".docx" => LlamaParseSupportedFileExtensions.Docx,
            ".dot" => LlamaParseSupportedFileExtensions.Dot,
            ".dotm" => LlamaParseSupportedFileExtensions.Dotm,
            ".dotx" => LlamaParseSupportedFileExtensions.Dotx,
            ".epub" => LlamaParseSupportedFileExtensions.Epub,
            ".et" => LlamaParseSupportedFileExtensions.Et,
            ".eth" => LlamaParseSupportedFileExtensions.Eth,
            ".fb2" => LlamaParseSupportedFileExtensions.Fb2,
            ".fbz" => LlamaParseSupportedFileExtensions.Fbz,
            ".fodg" => LlamaParseSupportedFileExtensions.Fodg,
            ".fodp" => LlamaParseSupportedFileExtensions.Fodp,
            ".fods" => LlamaParseSupportedFileExtensions.Fods,
            ".fodt" => LlamaParseSupportedFileExtensions.Fodt,
            ".fopd" => LlamaParseSupportedFileExtensions.Fopd,
            ".gif" => LlamaParseSupportedFileExtensions.Gif,
            ".heic" => LlamaParseSupportedFileExtensions.Heic,
            ".heif" => LlamaParseSupportedFileExtensions.Heif,
            ".htm" => LlamaParseSupportedFileExtensions.Htm,
            ".html" => LlamaParseSupportedFileExtensions.Html,
            ".htmlz" => LlamaParseSupportedFileExtensions.Htmlz,
            ".hwp" => LlamaParseSupportedFileExtensions.Hwp,
            ".jpeg" => LlamaParseSupportedFileExtensions.Jpeg,
            ".jpg" => LlamaParseSupportedFileExtensions.Jpg,
            ".key" => LlamaParseSupportedFileExtensions.Key,
            ".lit" => LlamaParseSupportedFileExtensions.Lit,
            ".lrf" => LlamaParseSupportedFileExtensions.Lrf,
            ".lwp" => LlamaParseSupportedFileExtensions.Lwp,
            ".m4a" => LlamaParseSupportedFileExtensions.M4a,
            ".mcw" => LlamaParseSupportedFileExtensions.Mcw,
            ".md" => LlamaParseSupportedFileExtensions.Md,
            ".mobi" => LlamaParseSupportedFileExtensions.Mobi,
            ".mp3" => LlamaParseSupportedFileExtensions.Mp3,
            ".mp4" => LlamaParseSupportedFileExtensions.Mp4,
            ".mpeg" => LlamaParseSupportedFileExtensions.Mpeg,
            ".mpga" => LlamaParseSupportedFileExtensions.Mpga,
            ".mw" => LlamaParseSupportedFileExtensions.Mw,
            ".mwd" => LlamaParseSupportedFileExtensions.Mwd,
            ".numbers" => LlamaParseSupportedFileExtensions.Numbers,
            ".odf" => LlamaParseSupportedFileExtensions.Odf,
            ".odg" => LlamaParseSupportedFileExtensions.Odg,
            ".odp" => LlamaParseSupportedFileExtensions.Odp,
            ".ods" => LlamaParseSupportedFileExtensions.Ods,
            ".odt" => LlamaParseSupportedFileExtensions.Odt,
            ".otg" => LlamaParseSupportedFileExtensions.Otg,
            ".otp" => LlamaParseSupportedFileExtensions.Otp,
            ".ots" => LlamaParseSupportedFileExtensions.Ots,
            ".ott" => LlamaParseSupportedFileExtensions.Ott,
            ".pages" => LlamaParseSupportedFileExtensions.Pages,
            ".pbd" => LlamaParseSupportedFileExtensions.Pbd,
            ".pdb" => LlamaParseSupportedFileExtensions.Pdb,
            ".pdf" => LlamaParseSupportedFileExtensions.Pdf,
            ".pml" => LlamaParseSupportedFileExtensions.Pml,
            ".png" => LlamaParseSupportedFileExtensions.Png,
            ".pot" => LlamaParseSupportedFileExtensions.Pot,
            ".potm" => LlamaParseSupportedFileExtensions.Potm,
            ".potx" => LlamaParseSupportedFileExtensions.Potx,
            ".ppt" => LlamaParseSupportedFileExtensions.Ppt,
            ".pptm" => LlamaParseSupportedFileExtensions.Pptm,
            ".pptx" => LlamaParseSupportedFileExtensions.Pptx,
            ".prc" => LlamaParseSupportedFileExtensions.Prc,
            ".prn" => LlamaParseSupportedFileExtensions.Prn,
            ".psw" => LlamaParseSupportedFileExtensions.Psw,
            ".qpw" => LlamaParseSupportedFileExtensions.Qpw,
            ".rb" => LlamaParseSupportedFileExtensions.Rb,
            ".rtf" => LlamaParseSupportedFileExtensions.Rtf,
            ".sda" => LlamaParseSupportedFileExtensions.Sda,
            ".sdd" => LlamaParseSupportedFileExtensions.Sdd,
            ".sdp" => LlamaParseSupportedFileExtensions.Sdp,
            ".sdw" => LlamaParseSupportedFileExtensions.Sdw,
            ".sgl" => LlamaParseSupportedFileExtensions.Sgl,
            ".slk" => LlamaParseSupportedFileExtensions.Slk,
            ".snb" => LlamaParseSupportedFileExtensions.Snb,
            ".stc" => LlamaParseSupportedFileExtensions.Stc,
            ".std" => LlamaParseSupportedFileExtensions.Std,
            ".sti" => LlamaParseSupportedFileExtensions.Sti,
            ".stw" => LlamaParseSupportedFileExtensions.Stw,
            ".svg" => LlamaParseSupportedFileExtensions.Svg,
            ".sxc" => LlamaParseSupportedFileExtensions.Sxc,
            ".sxd" => LlamaParseSupportedFileExtensions.Sxd,
            ".sxg" => LlamaParseSupportedFileExtensions.Sxg,
            ".sxi" => LlamaParseSupportedFileExtensions.Sxi,
            ".sxm" => LlamaParseSupportedFileExtensions.Sxm,
            ".sxw" => LlamaParseSupportedFileExtensions.Sxw,
            ".sylk" => LlamaParseSupportedFileExtensions.Sylk,
            ".tcr" => LlamaParseSupportedFileExtensions.Tcr,
            ".tif" => LlamaParseSupportedFileExtensions.Tif,
            ".tiff" => LlamaParseSupportedFileExtensions.Tiff,
            ".tsv" => LlamaParseSupportedFileExtensions.Tsv,
            ".txtz" => LlamaParseSupportedFileExtensions.Txtz,
            ".uof" => LlamaParseSupportedFileExtensions.Uof,
            ".uop" => LlamaParseSupportedFileExtensions.Uop,
            ".uos" => LlamaParseSupportedFileExtensions.Uos,
            ".uos1" => LlamaParseSupportedFileExtensions.Uos1,
            ".uos2" => LlamaParseSupportedFileExtensions.Uos2,
            ".uot" => LlamaParseSupportedFileExtensions.Uot,
            ".vdx" => LlamaParseSupportedFileExtensions.Vdx,
            ".vor" => LlamaParseSupportedFileExtensions.Vor,
            ".vsd" => LlamaParseSupportedFileExtensions.Vsd,
            ".vsdm" => LlamaParseSupportedFileExtensions.Vsdm,
            ".vsdx" => LlamaParseSupportedFileExtensions.Vsdx,
            ".wav" => LlamaParseSupportedFileExtensions.Wav,
            ".wb1" => LlamaParseSupportedFileExtensions.Wb1,
            ".wb2" => LlamaParseSupportedFileExtensions.Wb2,
            ".wb3" => LlamaParseSupportedFileExtensions.Wb3,
            ".webm" => LlamaParseSupportedFileExtensions.Webm,
            ".webp" => LlamaParseSupportedFileExtensions.Webp,
            ".wk1" => LlamaParseSupportedFileExtensions.Wk1,
            ".wk2" => LlamaParseSupportedFileExtensions.Wk2,
            ".wk3" => LlamaParseSupportedFileExtensions.Wk3,
            ".wk4" => LlamaParseSupportedFileExtensions.Wk4,
            ".wks" => LlamaParseSupportedFileExtensions.Wks,
            ".wn" => LlamaParseSupportedFileExtensions.Wn,
            ".wpd" => LlamaParseSupportedFileExtensions.Wpd,
            ".wps" => LlamaParseSupportedFileExtensions.Wps,
            ".wpt" => LlamaParseSupportedFileExtensions.Wpt,
            ".wq1" => LlamaParseSupportedFileExtensions.Wq1,
            ".wq2" => LlamaParseSupportedFileExtensions.Wq2,
            ".wri" => LlamaParseSupportedFileExtensions.Wri,
            ".xhtm" => LlamaParseSupportedFileExtensions.Xhtm,
            ".xlr" => LlamaParseSupportedFileExtensions.Xlr,
            ".xls" => LlamaParseSupportedFileExtensions.Xls,
            ".xlsb" => LlamaParseSupportedFileExtensions.Xlsb,
            ".xlsm" => LlamaParseSupportedFileExtensions.Xlsm,
            ".xlsx" => LlamaParseSupportedFileExtensions.Xlsx,
            ".xlw" => LlamaParseSupportedFileExtensions.Xlw,
            ".xml" => LlamaParseSupportedFileExtensions.Xml,
            ".yxmd" => LlamaParseSupportedFileExtensions.Yxmd,
            ".zabw" => LlamaParseSupportedFileExtensions.Zabw,
            _ => (LlamaParseSupportedFileExtensions)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        LlamaParseSupportedFileExtensions value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                LlamaParseSupportedFileExtensions.Abw => ".abw",
                LlamaParseSupportedFileExtensions.Awt => ".awt",
                LlamaParseSupportedFileExtensions.Azw => ".azw",
                LlamaParseSupportedFileExtensions.Azw3 => ".azw3",
                LlamaParseSupportedFileExtensions.Azw4 => ".azw4",
                LlamaParseSupportedFileExtensions.Bmp => ".bmp",
                LlamaParseSupportedFileExtensions.Cb7 => ".cb7",
                LlamaParseSupportedFileExtensions.Cbc => ".cbc",
                LlamaParseSupportedFileExtensions.Cbr => ".cbr",
                LlamaParseSupportedFileExtensions.Cbz => ".cbz",
                LlamaParseSupportedFileExtensions.Cgm => ".cgm",
                LlamaParseSupportedFileExtensions.Chm => ".chm",
                LlamaParseSupportedFileExtensions.Csv => ".csv",
                LlamaParseSupportedFileExtensions.Cwk => ".cwk",
                LlamaParseSupportedFileExtensions.Dbf => ".dbf",
                LlamaParseSupportedFileExtensions.Dif => ".dif",
                LlamaParseSupportedFileExtensions.Djvu => ".djvu",
                LlamaParseSupportedFileExtensions.Doc => ".doc",
                LlamaParseSupportedFileExtensions.Docm => ".docm",
                LlamaParseSupportedFileExtensions.Docx => ".docx",
                LlamaParseSupportedFileExtensions.Dot => ".dot",
                LlamaParseSupportedFileExtensions.Dotm => ".dotm",
                LlamaParseSupportedFileExtensions.Dotx => ".dotx",
                LlamaParseSupportedFileExtensions.Epub => ".epub",
                LlamaParseSupportedFileExtensions.Et => ".et",
                LlamaParseSupportedFileExtensions.Eth => ".eth",
                LlamaParseSupportedFileExtensions.Fb2 => ".fb2",
                LlamaParseSupportedFileExtensions.Fbz => ".fbz",
                LlamaParseSupportedFileExtensions.Fodg => ".fodg",
                LlamaParseSupportedFileExtensions.Fodp => ".fodp",
                LlamaParseSupportedFileExtensions.Fods => ".fods",
                LlamaParseSupportedFileExtensions.Fodt => ".fodt",
                LlamaParseSupportedFileExtensions.Fopd => ".fopd",
                LlamaParseSupportedFileExtensions.Gif => ".gif",
                LlamaParseSupportedFileExtensions.Heic => ".heic",
                LlamaParseSupportedFileExtensions.Heif => ".heif",
                LlamaParseSupportedFileExtensions.Htm => ".htm",
                LlamaParseSupportedFileExtensions.Html => ".html",
                LlamaParseSupportedFileExtensions.Htmlz => ".htmlz",
                LlamaParseSupportedFileExtensions.Hwp => ".hwp",
                LlamaParseSupportedFileExtensions.Jpeg => ".jpeg",
                LlamaParseSupportedFileExtensions.Jpg => ".jpg",
                LlamaParseSupportedFileExtensions.Key => ".key",
                LlamaParseSupportedFileExtensions.Lit => ".lit",
                LlamaParseSupportedFileExtensions.Lrf => ".lrf",
                LlamaParseSupportedFileExtensions.Lwp => ".lwp",
                LlamaParseSupportedFileExtensions.M4a => ".m4a",
                LlamaParseSupportedFileExtensions.Mcw => ".mcw",
                LlamaParseSupportedFileExtensions.Md => ".md",
                LlamaParseSupportedFileExtensions.Mobi => ".mobi",
                LlamaParseSupportedFileExtensions.Mp3 => ".mp3",
                LlamaParseSupportedFileExtensions.Mp4 => ".mp4",
                LlamaParseSupportedFileExtensions.Mpeg => ".mpeg",
                LlamaParseSupportedFileExtensions.Mpga => ".mpga",
                LlamaParseSupportedFileExtensions.Mw => ".mw",
                LlamaParseSupportedFileExtensions.Mwd => ".mwd",
                LlamaParseSupportedFileExtensions.Numbers => ".numbers",
                LlamaParseSupportedFileExtensions.Odf => ".odf",
                LlamaParseSupportedFileExtensions.Odg => ".odg",
                LlamaParseSupportedFileExtensions.Odp => ".odp",
                LlamaParseSupportedFileExtensions.Ods => ".ods",
                LlamaParseSupportedFileExtensions.Odt => ".odt",
                LlamaParseSupportedFileExtensions.Otg => ".otg",
                LlamaParseSupportedFileExtensions.Otp => ".otp",
                LlamaParseSupportedFileExtensions.Ots => ".ots",
                LlamaParseSupportedFileExtensions.Ott => ".ott",
                LlamaParseSupportedFileExtensions.Pages => ".pages",
                LlamaParseSupportedFileExtensions.Pbd => ".pbd",
                LlamaParseSupportedFileExtensions.Pdb => ".pdb",
                LlamaParseSupportedFileExtensions.Pdf => ".pdf",
                LlamaParseSupportedFileExtensions.Pml => ".pml",
                LlamaParseSupportedFileExtensions.Png => ".png",
                LlamaParseSupportedFileExtensions.Pot => ".pot",
                LlamaParseSupportedFileExtensions.Potm => ".potm",
                LlamaParseSupportedFileExtensions.Potx => ".potx",
                LlamaParseSupportedFileExtensions.Ppt => ".ppt",
                LlamaParseSupportedFileExtensions.Pptm => ".pptm",
                LlamaParseSupportedFileExtensions.Pptx => ".pptx",
                LlamaParseSupportedFileExtensions.Prc => ".prc",
                LlamaParseSupportedFileExtensions.Prn => ".prn",
                LlamaParseSupportedFileExtensions.Psw => ".psw",
                LlamaParseSupportedFileExtensions.Qpw => ".qpw",
                LlamaParseSupportedFileExtensions.Rb => ".rb",
                LlamaParseSupportedFileExtensions.Rtf => ".rtf",
                LlamaParseSupportedFileExtensions.Sda => ".sda",
                LlamaParseSupportedFileExtensions.Sdd => ".sdd",
                LlamaParseSupportedFileExtensions.Sdp => ".sdp",
                LlamaParseSupportedFileExtensions.Sdw => ".sdw",
                LlamaParseSupportedFileExtensions.Sgl => ".sgl",
                LlamaParseSupportedFileExtensions.Slk => ".slk",
                LlamaParseSupportedFileExtensions.Snb => ".snb",
                LlamaParseSupportedFileExtensions.Stc => ".stc",
                LlamaParseSupportedFileExtensions.Std => ".std",
                LlamaParseSupportedFileExtensions.Sti => ".sti",
                LlamaParseSupportedFileExtensions.Stw => ".stw",
                LlamaParseSupportedFileExtensions.Svg => ".svg",
                LlamaParseSupportedFileExtensions.Sxc => ".sxc",
                LlamaParseSupportedFileExtensions.Sxd => ".sxd",
                LlamaParseSupportedFileExtensions.Sxg => ".sxg",
                LlamaParseSupportedFileExtensions.Sxi => ".sxi",
                LlamaParseSupportedFileExtensions.Sxm => ".sxm",
                LlamaParseSupportedFileExtensions.Sxw => ".sxw",
                LlamaParseSupportedFileExtensions.Sylk => ".sylk",
                LlamaParseSupportedFileExtensions.Tcr => ".tcr",
                LlamaParseSupportedFileExtensions.Tif => ".tif",
                LlamaParseSupportedFileExtensions.Tiff => ".tiff",
                LlamaParseSupportedFileExtensions.Tsv => ".tsv",
                LlamaParseSupportedFileExtensions.Txtz => ".txtz",
                LlamaParseSupportedFileExtensions.Uof => ".uof",
                LlamaParseSupportedFileExtensions.Uop => ".uop",
                LlamaParseSupportedFileExtensions.Uos => ".uos",
                LlamaParseSupportedFileExtensions.Uos1 => ".uos1",
                LlamaParseSupportedFileExtensions.Uos2 => ".uos2",
                LlamaParseSupportedFileExtensions.Uot => ".uot",
                LlamaParseSupportedFileExtensions.Vdx => ".vdx",
                LlamaParseSupportedFileExtensions.Vor => ".vor",
                LlamaParseSupportedFileExtensions.Vsd => ".vsd",
                LlamaParseSupportedFileExtensions.Vsdm => ".vsdm",
                LlamaParseSupportedFileExtensions.Vsdx => ".vsdx",
                LlamaParseSupportedFileExtensions.Wav => ".wav",
                LlamaParseSupportedFileExtensions.Wb1 => ".wb1",
                LlamaParseSupportedFileExtensions.Wb2 => ".wb2",
                LlamaParseSupportedFileExtensions.Wb3 => ".wb3",
                LlamaParseSupportedFileExtensions.Webm => ".webm",
                LlamaParseSupportedFileExtensions.Webp => ".webp",
                LlamaParseSupportedFileExtensions.Wk1 => ".wk1",
                LlamaParseSupportedFileExtensions.Wk2 => ".wk2",
                LlamaParseSupportedFileExtensions.Wk3 => ".wk3",
                LlamaParseSupportedFileExtensions.Wk4 => ".wk4",
                LlamaParseSupportedFileExtensions.Wks => ".wks",
                LlamaParseSupportedFileExtensions.Wn => ".wn",
                LlamaParseSupportedFileExtensions.Wpd => ".wpd",
                LlamaParseSupportedFileExtensions.Wps => ".wps",
                LlamaParseSupportedFileExtensions.Wpt => ".wpt",
                LlamaParseSupportedFileExtensions.Wq1 => ".wq1",
                LlamaParseSupportedFileExtensions.Wq2 => ".wq2",
                LlamaParseSupportedFileExtensions.Wri => ".wri",
                LlamaParseSupportedFileExtensions.Xhtm => ".xhtm",
                LlamaParseSupportedFileExtensions.Xlr => ".xlr",
                LlamaParseSupportedFileExtensions.Xls => ".xls",
                LlamaParseSupportedFileExtensions.Xlsb => ".xlsb",
                LlamaParseSupportedFileExtensions.Xlsm => ".xlsm",
                LlamaParseSupportedFileExtensions.Xlsx => ".xlsx",
                LlamaParseSupportedFileExtensions.Xlw => ".xlw",
                LlamaParseSupportedFileExtensions.Xml => ".xml",
                LlamaParseSupportedFileExtensions.Yxmd => ".yxmd",
                LlamaParseSupportedFileExtensions.Zabw => ".zabw",
                _ => throw new LlamaCloudInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
