using System.Text.Json;
using System.Text.Json.Serialization;
using LlamaCloud.Exceptions;
using System = System;

namespace LlamaCloud.Models.Parsing;

/// <summary>
/// Enum for representing the languages supported by the parser.
/// </summary>
[JsonConverter(typeof(ParsingLanguagesConverter))]
public enum ParsingLanguages
{
    Abq,
    Ady,
    Af,
    Ang,
    Ar,
    As,
    Ava,
    Az,
    Be,
    Bg,
    Bgc,
    Bh,
    Bho,
    Bn,
    Bs,
    ChSim,
    ChTra,
    Che,
    Cs,
    Cy,
    Da,
    Dar,
    De,
    En,
    Es,
    Et,
    Fa,
    Fr,
    Ga,
    Gom,
    Hi,
    Hr,
    Hu,
    ID,
    Inh,
    Is,
    It,
    Ja,
    Kbd,
    Kn,
    Ko,
    Ku,
    La,
    Lbe,
    Lez,
    Lt,
    Lv,
    Mah,
    Mai,
    Mi,
    Mn,
    Mni,
    Mr,
    Ms,
    Mt,
    Ne,
    New,
    Nl,
    No,
    Oc,
    Pi,
    Pl,
    Pt,
    Ro,
    RsCyrillic,
    RsLatin,
    Ru,
    Sa,
    Sck,
    Sk,
    Sl,
    Sq,
    Sv,
    Sw,
    Ta,
    Tab,
    Te,
    Th,
    Tjk,
    Tl,
    Tr,
    Ug,
    Uk,
    Ur,
    Uz,
    Vi,
}

sealed class ParsingLanguagesConverter : JsonConverter<ParsingLanguages>
{
    public override ParsingLanguages Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "abq" => ParsingLanguages.Abq,
            "ady" => ParsingLanguages.Ady,
            "af" => ParsingLanguages.Af,
            "ang" => ParsingLanguages.Ang,
            "ar" => ParsingLanguages.Ar,
            "as" => ParsingLanguages.As,
            "ava" => ParsingLanguages.Ava,
            "az" => ParsingLanguages.Az,
            "be" => ParsingLanguages.Be,
            "bg" => ParsingLanguages.Bg,
            "bgc" => ParsingLanguages.Bgc,
            "bh" => ParsingLanguages.Bh,
            "bho" => ParsingLanguages.Bho,
            "bn" => ParsingLanguages.Bn,
            "bs" => ParsingLanguages.Bs,
            "ch_sim" => ParsingLanguages.ChSim,
            "ch_tra" => ParsingLanguages.ChTra,
            "che" => ParsingLanguages.Che,
            "cs" => ParsingLanguages.Cs,
            "cy" => ParsingLanguages.Cy,
            "da" => ParsingLanguages.Da,
            "dar" => ParsingLanguages.Dar,
            "de" => ParsingLanguages.De,
            "en" => ParsingLanguages.En,
            "es" => ParsingLanguages.Es,
            "et" => ParsingLanguages.Et,
            "fa" => ParsingLanguages.Fa,
            "fr" => ParsingLanguages.Fr,
            "ga" => ParsingLanguages.Ga,
            "gom" => ParsingLanguages.Gom,
            "hi" => ParsingLanguages.Hi,
            "hr" => ParsingLanguages.Hr,
            "hu" => ParsingLanguages.Hu,
            "id" => ParsingLanguages.ID,
            "inh" => ParsingLanguages.Inh,
            "is" => ParsingLanguages.Is,
            "it" => ParsingLanguages.It,
            "ja" => ParsingLanguages.Ja,
            "kbd" => ParsingLanguages.Kbd,
            "kn" => ParsingLanguages.Kn,
            "ko" => ParsingLanguages.Ko,
            "ku" => ParsingLanguages.Ku,
            "la" => ParsingLanguages.La,
            "lbe" => ParsingLanguages.Lbe,
            "lez" => ParsingLanguages.Lez,
            "lt" => ParsingLanguages.Lt,
            "lv" => ParsingLanguages.Lv,
            "mah" => ParsingLanguages.Mah,
            "mai" => ParsingLanguages.Mai,
            "mi" => ParsingLanguages.Mi,
            "mn" => ParsingLanguages.Mn,
            "mni" => ParsingLanguages.Mni,
            "mr" => ParsingLanguages.Mr,
            "ms" => ParsingLanguages.Ms,
            "mt" => ParsingLanguages.Mt,
            "ne" => ParsingLanguages.Ne,
            "new" => ParsingLanguages.New,
            "nl" => ParsingLanguages.Nl,
            "no" => ParsingLanguages.No,
            "oc" => ParsingLanguages.Oc,
            "pi" => ParsingLanguages.Pi,
            "pl" => ParsingLanguages.Pl,
            "pt" => ParsingLanguages.Pt,
            "ro" => ParsingLanguages.Ro,
            "rs_cyrillic" => ParsingLanguages.RsCyrillic,
            "rs_latin" => ParsingLanguages.RsLatin,
            "ru" => ParsingLanguages.Ru,
            "sa" => ParsingLanguages.Sa,
            "sck" => ParsingLanguages.Sck,
            "sk" => ParsingLanguages.Sk,
            "sl" => ParsingLanguages.Sl,
            "sq" => ParsingLanguages.Sq,
            "sv" => ParsingLanguages.Sv,
            "sw" => ParsingLanguages.Sw,
            "ta" => ParsingLanguages.Ta,
            "tab" => ParsingLanguages.Tab,
            "te" => ParsingLanguages.Te,
            "th" => ParsingLanguages.Th,
            "tjk" => ParsingLanguages.Tjk,
            "tl" => ParsingLanguages.Tl,
            "tr" => ParsingLanguages.Tr,
            "ug" => ParsingLanguages.Ug,
            "uk" => ParsingLanguages.Uk,
            "ur" => ParsingLanguages.Ur,
            "uz" => ParsingLanguages.Uz,
            "vi" => ParsingLanguages.Vi,
            _ => (ParsingLanguages)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ParsingLanguages value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                ParsingLanguages.Abq => "abq",
                ParsingLanguages.Ady => "ady",
                ParsingLanguages.Af => "af",
                ParsingLanguages.Ang => "ang",
                ParsingLanguages.Ar => "ar",
                ParsingLanguages.As => "as",
                ParsingLanguages.Ava => "ava",
                ParsingLanguages.Az => "az",
                ParsingLanguages.Be => "be",
                ParsingLanguages.Bg => "bg",
                ParsingLanguages.Bgc => "bgc",
                ParsingLanguages.Bh => "bh",
                ParsingLanguages.Bho => "bho",
                ParsingLanguages.Bn => "bn",
                ParsingLanguages.Bs => "bs",
                ParsingLanguages.ChSim => "ch_sim",
                ParsingLanguages.ChTra => "ch_tra",
                ParsingLanguages.Che => "che",
                ParsingLanguages.Cs => "cs",
                ParsingLanguages.Cy => "cy",
                ParsingLanguages.Da => "da",
                ParsingLanguages.Dar => "dar",
                ParsingLanguages.De => "de",
                ParsingLanguages.En => "en",
                ParsingLanguages.Es => "es",
                ParsingLanguages.Et => "et",
                ParsingLanguages.Fa => "fa",
                ParsingLanguages.Fr => "fr",
                ParsingLanguages.Ga => "ga",
                ParsingLanguages.Gom => "gom",
                ParsingLanguages.Hi => "hi",
                ParsingLanguages.Hr => "hr",
                ParsingLanguages.Hu => "hu",
                ParsingLanguages.ID => "id",
                ParsingLanguages.Inh => "inh",
                ParsingLanguages.Is => "is",
                ParsingLanguages.It => "it",
                ParsingLanguages.Ja => "ja",
                ParsingLanguages.Kbd => "kbd",
                ParsingLanguages.Kn => "kn",
                ParsingLanguages.Ko => "ko",
                ParsingLanguages.Ku => "ku",
                ParsingLanguages.La => "la",
                ParsingLanguages.Lbe => "lbe",
                ParsingLanguages.Lez => "lez",
                ParsingLanguages.Lt => "lt",
                ParsingLanguages.Lv => "lv",
                ParsingLanguages.Mah => "mah",
                ParsingLanguages.Mai => "mai",
                ParsingLanguages.Mi => "mi",
                ParsingLanguages.Mn => "mn",
                ParsingLanguages.Mni => "mni",
                ParsingLanguages.Mr => "mr",
                ParsingLanguages.Ms => "ms",
                ParsingLanguages.Mt => "mt",
                ParsingLanguages.Ne => "ne",
                ParsingLanguages.New => "new",
                ParsingLanguages.Nl => "nl",
                ParsingLanguages.No => "no",
                ParsingLanguages.Oc => "oc",
                ParsingLanguages.Pi => "pi",
                ParsingLanguages.Pl => "pl",
                ParsingLanguages.Pt => "pt",
                ParsingLanguages.Ro => "ro",
                ParsingLanguages.RsCyrillic => "rs_cyrillic",
                ParsingLanguages.RsLatin => "rs_latin",
                ParsingLanguages.Ru => "ru",
                ParsingLanguages.Sa => "sa",
                ParsingLanguages.Sck => "sck",
                ParsingLanguages.Sk => "sk",
                ParsingLanguages.Sl => "sl",
                ParsingLanguages.Sq => "sq",
                ParsingLanguages.Sv => "sv",
                ParsingLanguages.Sw => "sw",
                ParsingLanguages.Ta => "ta",
                ParsingLanguages.Tab => "tab",
                ParsingLanguages.Te => "te",
                ParsingLanguages.Th => "th",
                ParsingLanguages.Tjk => "tjk",
                ParsingLanguages.Tl => "tl",
                ParsingLanguages.Tr => "tr",
                ParsingLanguages.Ug => "ug",
                ParsingLanguages.Uk => "uk",
                ParsingLanguages.Ur => "ur",
                ParsingLanguages.Uz => "uz",
                ParsingLanguages.Vi => "vi",
                _ => throw new LlamaCloudInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
