using System.Text.Json;
using LlamaIndex.LlamaCloud.Core;
using LlamaIndex.LlamaCloud.Exceptions;
using LlamaIndex.LlamaCloud.Models.Parsing;

namespace LlamaIndex.LlamaCloud.Tests.Models.Parsing;

public class LlamaParseSupportedFileExtensionsTest : TestBase
{
    [Theory]
    [InlineData(LlamaParseSupportedFileExtensions.Abw)]
    [InlineData(LlamaParseSupportedFileExtensions.Awt)]
    [InlineData(LlamaParseSupportedFileExtensions.Azw)]
    [InlineData(LlamaParseSupportedFileExtensions.Azw3)]
    [InlineData(LlamaParseSupportedFileExtensions.Azw4)]
    [InlineData(LlamaParseSupportedFileExtensions.Bmp)]
    [InlineData(LlamaParseSupportedFileExtensions.Cb7)]
    [InlineData(LlamaParseSupportedFileExtensions.Cbc)]
    [InlineData(LlamaParseSupportedFileExtensions.Cbr)]
    [InlineData(LlamaParseSupportedFileExtensions.Cbz)]
    [InlineData(LlamaParseSupportedFileExtensions.Cgm)]
    [InlineData(LlamaParseSupportedFileExtensions.Chm)]
    [InlineData(LlamaParseSupportedFileExtensions.Csv)]
    [InlineData(LlamaParseSupportedFileExtensions.Cwk)]
    [InlineData(LlamaParseSupportedFileExtensions.Dbf)]
    [InlineData(LlamaParseSupportedFileExtensions.Dif)]
    [InlineData(LlamaParseSupportedFileExtensions.Djvu)]
    [InlineData(LlamaParseSupportedFileExtensions.Doc)]
    [InlineData(LlamaParseSupportedFileExtensions.Docm)]
    [InlineData(LlamaParseSupportedFileExtensions.Docx)]
    [InlineData(LlamaParseSupportedFileExtensions.Dot)]
    [InlineData(LlamaParseSupportedFileExtensions.Dotm)]
    [InlineData(LlamaParseSupportedFileExtensions.Dotx)]
    [InlineData(LlamaParseSupportedFileExtensions.Epub)]
    [InlineData(LlamaParseSupportedFileExtensions.Et)]
    [InlineData(LlamaParseSupportedFileExtensions.Eth)]
    [InlineData(LlamaParseSupportedFileExtensions.Fb2)]
    [InlineData(LlamaParseSupportedFileExtensions.Fbz)]
    [InlineData(LlamaParseSupportedFileExtensions.Fodg)]
    [InlineData(LlamaParseSupportedFileExtensions.Fodp)]
    [InlineData(LlamaParseSupportedFileExtensions.Fods)]
    [InlineData(LlamaParseSupportedFileExtensions.Fodt)]
    [InlineData(LlamaParseSupportedFileExtensions.Fopd)]
    [InlineData(LlamaParseSupportedFileExtensions.Gif)]
    [InlineData(LlamaParseSupportedFileExtensions.Heic)]
    [InlineData(LlamaParseSupportedFileExtensions.Heif)]
    [InlineData(LlamaParseSupportedFileExtensions.Htm)]
    [InlineData(LlamaParseSupportedFileExtensions.Html)]
    [InlineData(LlamaParseSupportedFileExtensions.Htmlz)]
    [InlineData(LlamaParseSupportedFileExtensions.Hwp)]
    [InlineData(LlamaParseSupportedFileExtensions.Jpeg)]
    [InlineData(LlamaParseSupportedFileExtensions.Jpg)]
    [InlineData(LlamaParseSupportedFileExtensions.Key)]
    [InlineData(LlamaParseSupportedFileExtensions.Lit)]
    [InlineData(LlamaParseSupportedFileExtensions.Lrf)]
    [InlineData(LlamaParseSupportedFileExtensions.Lwp)]
    [InlineData(LlamaParseSupportedFileExtensions.M4a)]
    [InlineData(LlamaParseSupportedFileExtensions.Mcw)]
    [InlineData(LlamaParseSupportedFileExtensions.Md)]
    [InlineData(LlamaParseSupportedFileExtensions.Mobi)]
    [InlineData(LlamaParseSupportedFileExtensions.Mp3)]
    [InlineData(LlamaParseSupportedFileExtensions.Mp4)]
    [InlineData(LlamaParseSupportedFileExtensions.Mpeg)]
    [InlineData(LlamaParseSupportedFileExtensions.Mpga)]
    [InlineData(LlamaParseSupportedFileExtensions.Mw)]
    [InlineData(LlamaParseSupportedFileExtensions.Mwd)]
    [InlineData(LlamaParseSupportedFileExtensions.Numbers)]
    [InlineData(LlamaParseSupportedFileExtensions.Odf)]
    [InlineData(LlamaParseSupportedFileExtensions.Odg)]
    [InlineData(LlamaParseSupportedFileExtensions.Odp)]
    [InlineData(LlamaParseSupportedFileExtensions.Ods)]
    [InlineData(LlamaParseSupportedFileExtensions.Odt)]
    [InlineData(LlamaParseSupportedFileExtensions.Otg)]
    [InlineData(LlamaParseSupportedFileExtensions.Otp)]
    [InlineData(LlamaParseSupportedFileExtensions.Ots)]
    [InlineData(LlamaParseSupportedFileExtensions.Ott)]
    [InlineData(LlamaParseSupportedFileExtensions.Pages)]
    [InlineData(LlamaParseSupportedFileExtensions.Pbd)]
    [InlineData(LlamaParseSupportedFileExtensions.Pdb)]
    [InlineData(LlamaParseSupportedFileExtensions.Pdf)]
    [InlineData(LlamaParseSupportedFileExtensions.Pml)]
    [InlineData(LlamaParseSupportedFileExtensions.Png)]
    [InlineData(LlamaParseSupportedFileExtensions.Pot)]
    [InlineData(LlamaParseSupportedFileExtensions.Potm)]
    [InlineData(LlamaParseSupportedFileExtensions.Potx)]
    [InlineData(LlamaParseSupportedFileExtensions.Ppt)]
    [InlineData(LlamaParseSupportedFileExtensions.Pptm)]
    [InlineData(LlamaParseSupportedFileExtensions.Pptx)]
    [InlineData(LlamaParseSupportedFileExtensions.Prc)]
    [InlineData(LlamaParseSupportedFileExtensions.Prn)]
    [InlineData(LlamaParseSupportedFileExtensions.Psw)]
    [InlineData(LlamaParseSupportedFileExtensions.Qpw)]
    [InlineData(LlamaParseSupportedFileExtensions.Rb)]
    [InlineData(LlamaParseSupportedFileExtensions.Rtf)]
    [InlineData(LlamaParseSupportedFileExtensions.Sda)]
    [InlineData(LlamaParseSupportedFileExtensions.Sdd)]
    [InlineData(LlamaParseSupportedFileExtensions.Sdp)]
    [InlineData(LlamaParseSupportedFileExtensions.Sdw)]
    [InlineData(LlamaParseSupportedFileExtensions.Sgl)]
    [InlineData(LlamaParseSupportedFileExtensions.Slk)]
    [InlineData(LlamaParseSupportedFileExtensions.Snb)]
    [InlineData(LlamaParseSupportedFileExtensions.Stc)]
    [InlineData(LlamaParseSupportedFileExtensions.Std)]
    [InlineData(LlamaParseSupportedFileExtensions.Sti)]
    [InlineData(LlamaParseSupportedFileExtensions.Stw)]
    [InlineData(LlamaParseSupportedFileExtensions.Svg)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxc)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxd)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxg)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxi)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxm)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxw)]
    [InlineData(LlamaParseSupportedFileExtensions.Sylk)]
    [InlineData(LlamaParseSupportedFileExtensions.Tcr)]
    [InlineData(LlamaParseSupportedFileExtensions.Tif)]
    [InlineData(LlamaParseSupportedFileExtensions.Tiff)]
    [InlineData(LlamaParseSupportedFileExtensions.Tsv)]
    [InlineData(LlamaParseSupportedFileExtensions.Txtz)]
    [InlineData(LlamaParseSupportedFileExtensions.Uof)]
    [InlineData(LlamaParseSupportedFileExtensions.Uop)]
    [InlineData(LlamaParseSupportedFileExtensions.Uos)]
    [InlineData(LlamaParseSupportedFileExtensions.Uos1)]
    [InlineData(LlamaParseSupportedFileExtensions.Uos2)]
    [InlineData(LlamaParseSupportedFileExtensions.Uot)]
    [InlineData(LlamaParseSupportedFileExtensions.Vdx)]
    [InlineData(LlamaParseSupportedFileExtensions.Vor)]
    [InlineData(LlamaParseSupportedFileExtensions.Vsd)]
    [InlineData(LlamaParseSupportedFileExtensions.Vsdm)]
    [InlineData(LlamaParseSupportedFileExtensions.Vsdx)]
    [InlineData(LlamaParseSupportedFileExtensions.Wav)]
    [InlineData(LlamaParseSupportedFileExtensions.Wb1)]
    [InlineData(LlamaParseSupportedFileExtensions.Wb2)]
    [InlineData(LlamaParseSupportedFileExtensions.Wb3)]
    [InlineData(LlamaParseSupportedFileExtensions.Webm)]
    [InlineData(LlamaParseSupportedFileExtensions.Webp)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk1)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk2)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk3)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk4)]
    [InlineData(LlamaParseSupportedFileExtensions.Wks)]
    [InlineData(LlamaParseSupportedFileExtensions.Wn)]
    [InlineData(LlamaParseSupportedFileExtensions.Wpd)]
    [InlineData(LlamaParseSupportedFileExtensions.Wps)]
    [InlineData(LlamaParseSupportedFileExtensions.Wpt)]
    [InlineData(LlamaParseSupportedFileExtensions.Wq1)]
    [InlineData(LlamaParseSupportedFileExtensions.Wq2)]
    [InlineData(LlamaParseSupportedFileExtensions.Wri)]
    [InlineData(LlamaParseSupportedFileExtensions.Xhtm)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlr)]
    [InlineData(LlamaParseSupportedFileExtensions.Xls)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlsb)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlsm)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlsx)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlw)]
    [InlineData(LlamaParseSupportedFileExtensions.Xml)]
    [InlineData(LlamaParseSupportedFileExtensions.Yxmd)]
    [InlineData(LlamaParseSupportedFileExtensions.Zabw)]
    public void Validation_Works(LlamaParseSupportedFileExtensions rawValue)
    {
        // force implicit conversion because Theory can't do that for us
        ApiEnum<string, LlamaParseSupportedFileExtensions> value = rawValue;
        value.Validate();
    }

    [Fact]
    public void InvalidEnumValidationThrows_Works()
    {
        var value = JsonSerializer.Deserialize<ApiEnum<string, LlamaParseSupportedFileExtensions>>(
            JsonSerializer.SerializeToElement("invalid value"),
            ModelBase.SerializerOptions
        );

        Assert.NotNull(value);
        Assert.Throws<LlamaCloudInvalidDataException>(() => value.Validate());
    }

    [Theory]
    [InlineData(LlamaParseSupportedFileExtensions.Abw)]
    [InlineData(LlamaParseSupportedFileExtensions.Awt)]
    [InlineData(LlamaParseSupportedFileExtensions.Azw)]
    [InlineData(LlamaParseSupportedFileExtensions.Azw3)]
    [InlineData(LlamaParseSupportedFileExtensions.Azw4)]
    [InlineData(LlamaParseSupportedFileExtensions.Bmp)]
    [InlineData(LlamaParseSupportedFileExtensions.Cb7)]
    [InlineData(LlamaParseSupportedFileExtensions.Cbc)]
    [InlineData(LlamaParseSupportedFileExtensions.Cbr)]
    [InlineData(LlamaParseSupportedFileExtensions.Cbz)]
    [InlineData(LlamaParseSupportedFileExtensions.Cgm)]
    [InlineData(LlamaParseSupportedFileExtensions.Chm)]
    [InlineData(LlamaParseSupportedFileExtensions.Csv)]
    [InlineData(LlamaParseSupportedFileExtensions.Cwk)]
    [InlineData(LlamaParseSupportedFileExtensions.Dbf)]
    [InlineData(LlamaParseSupportedFileExtensions.Dif)]
    [InlineData(LlamaParseSupportedFileExtensions.Djvu)]
    [InlineData(LlamaParseSupportedFileExtensions.Doc)]
    [InlineData(LlamaParseSupportedFileExtensions.Docm)]
    [InlineData(LlamaParseSupportedFileExtensions.Docx)]
    [InlineData(LlamaParseSupportedFileExtensions.Dot)]
    [InlineData(LlamaParseSupportedFileExtensions.Dotm)]
    [InlineData(LlamaParseSupportedFileExtensions.Dotx)]
    [InlineData(LlamaParseSupportedFileExtensions.Epub)]
    [InlineData(LlamaParseSupportedFileExtensions.Et)]
    [InlineData(LlamaParseSupportedFileExtensions.Eth)]
    [InlineData(LlamaParseSupportedFileExtensions.Fb2)]
    [InlineData(LlamaParseSupportedFileExtensions.Fbz)]
    [InlineData(LlamaParseSupportedFileExtensions.Fodg)]
    [InlineData(LlamaParseSupportedFileExtensions.Fodp)]
    [InlineData(LlamaParseSupportedFileExtensions.Fods)]
    [InlineData(LlamaParseSupportedFileExtensions.Fodt)]
    [InlineData(LlamaParseSupportedFileExtensions.Fopd)]
    [InlineData(LlamaParseSupportedFileExtensions.Gif)]
    [InlineData(LlamaParseSupportedFileExtensions.Heic)]
    [InlineData(LlamaParseSupportedFileExtensions.Heif)]
    [InlineData(LlamaParseSupportedFileExtensions.Htm)]
    [InlineData(LlamaParseSupportedFileExtensions.Html)]
    [InlineData(LlamaParseSupportedFileExtensions.Htmlz)]
    [InlineData(LlamaParseSupportedFileExtensions.Hwp)]
    [InlineData(LlamaParseSupportedFileExtensions.Jpeg)]
    [InlineData(LlamaParseSupportedFileExtensions.Jpg)]
    [InlineData(LlamaParseSupportedFileExtensions.Key)]
    [InlineData(LlamaParseSupportedFileExtensions.Lit)]
    [InlineData(LlamaParseSupportedFileExtensions.Lrf)]
    [InlineData(LlamaParseSupportedFileExtensions.Lwp)]
    [InlineData(LlamaParseSupportedFileExtensions.M4a)]
    [InlineData(LlamaParseSupportedFileExtensions.Mcw)]
    [InlineData(LlamaParseSupportedFileExtensions.Md)]
    [InlineData(LlamaParseSupportedFileExtensions.Mobi)]
    [InlineData(LlamaParseSupportedFileExtensions.Mp3)]
    [InlineData(LlamaParseSupportedFileExtensions.Mp4)]
    [InlineData(LlamaParseSupportedFileExtensions.Mpeg)]
    [InlineData(LlamaParseSupportedFileExtensions.Mpga)]
    [InlineData(LlamaParseSupportedFileExtensions.Mw)]
    [InlineData(LlamaParseSupportedFileExtensions.Mwd)]
    [InlineData(LlamaParseSupportedFileExtensions.Numbers)]
    [InlineData(LlamaParseSupportedFileExtensions.Odf)]
    [InlineData(LlamaParseSupportedFileExtensions.Odg)]
    [InlineData(LlamaParseSupportedFileExtensions.Odp)]
    [InlineData(LlamaParseSupportedFileExtensions.Ods)]
    [InlineData(LlamaParseSupportedFileExtensions.Odt)]
    [InlineData(LlamaParseSupportedFileExtensions.Otg)]
    [InlineData(LlamaParseSupportedFileExtensions.Otp)]
    [InlineData(LlamaParseSupportedFileExtensions.Ots)]
    [InlineData(LlamaParseSupportedFileExtensions.Ott)]
    [InlineData(LlamaParseSupportedFileExtensions.Pages)]
    [InlineData(LlamaParseSupportedFileExtensions.Pbd)]
    [InlineData(LlamaParseSupportedFileExtensions.Pdb)]
    [InlineData(LlamaParseSupportedFileExtensions.Pdf)]
    [InlineData(LlamaParseSupportedFileExtensions.Pml)]
    [InlineData(LlamaParseSupportedFileExtensions.Png)]
    [InlineData(LlamaParseSupportedFileExtensions.Pot)]
    [InlineData(LlamaParseSupportedFileExtensions.Potm)]
    [InlineData(LlamaParseSupportedFileExtensions.Potx)]
    [InlineData(LlamaParseSupportedFileExtensions.Ppt)]
    [InlineData(LlamaParseSupportedFileExtensions.Pptm)]
    [InlineData(LlamaParseSupportedFileExtensions.Pptx)]
    [InlineData(LlamaParseSupportedFileExtensions.Prc)]
    [InlineData(LlamaParseSupportedFileExtensions.Prn)]
    [InlineData(LlamaParseSupportedFileExtensions.Psw)]
    [InlineData(LlamaParseSupportedFileExtensions.Qpw)]
    [InlineData(LlamaParseSupportedFileExtensions.Rb)]
    [InlineData(LlamaParseSupportedFileExtensions.Rtf)]
    [InlineData(LlamaParseSupportedFileExtensions.Sda)]
    [InlineData(LlamaParseSupportedFileExtensions.Sdd)]
    [InlineData(LlamaParseSupportedFileExtensions.Sdp)]
    [InlineData(LlamaParseSupportedFileExtensions.Sdw)]
    [InlineData(LlamaParseSupportedFileExtensions.Sgl)]
    [InlineData(LlamaParseSupportedFileExtensions.Slk)]
    [InlineData(LlamaParseSupportedFileExtensions.Snb)]
    [InlineData(LlamaParseSupportedFileExtensions.Stc)]
    [InlineData(LlamaParseSupportedFileExtensions.Std)]
    [InlineData(LlamaParseSupportedFileExtensions.Sti)]
    [InlineData(LlamaParseSupportedFileExtensions.Stw)]
    [InlineData(LlamaParseSupportedFileExtensions.Svg)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxc)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxd)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxg)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxi)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxm)]
    [InlineData(LlamaParseSupportedFileExtensions.Sxw)]
    [InlineData(LlamaParseSupportedFileExtensions.Sylk)]
    [InlineData(LlamaParseSupportedFileExtensions.Tcr)]
    [InlineData(LlamaParseSupportedFileExtensions.Tif)]
    [InlineData(LlamaParseSupportedFileExtensions.Tiff)]
    [InlineData(LlamaParseSupportedFileExtensions.Tsv)]
    [InlineData(LlamaParseSupportedFileExtensions.Txtz)]
    [InlineData(LlamaParseSupportedFileExtensions.Uof)]
    [InlineData(LlamaParseSupportedFileExtensions.Uop)]
    [InlineData(LlamaParseSupportedFileExtensions.Uos)]
    [InlineData(LlamaParseSupportedFileExtensions.Uos1)]
    [InlineData(LlamaParseSupportedFileExtensions.Uos2)]
    [InlineData(LlamaParseSupportedFileExtensions.Uot)]
    [InlineData(LlamaParseSupportedFileExtensions.Vdx)]
    [InlineData(LlamaParseSupportedFileExtensions.Vor)]
    [InlineData(LlamaParseSupportedFileExtensions.Vsd)]
    [InlineData(LlamaParseSupportedFileExtensions.Vsdm)]
    [InlineData(LlamaParseSupportedFileExtensions.Vsdx)]
    [InlineData(LlamaParseSupportedFileExtensions.Wav)]
    [InlineData(LlamaParseSupportedFileExtensions.Wb1)]
    [InlineData(LlamaParseSupportedFileExtensions.Wb2)]
    [InlineData(LlamaParseSupportedFileExtensions.Wb3)]
    [InlineData(LlamaParseSupportedFileExtensions.Webm)]
    [InlineData(LlamaParseSupportedFileExtensions.Webp)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk1)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk2)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk3)]
    [InlineData(LlamaParseSupportedFileExtensions.Wk4)]
    [InlineData(LlamaParseSupportedFileExtensions.Wks)]
    [InlineData(LlamaParseSupportedFileExtensions.Wn)]
    [InlineData(LlamaParseSupportedFileExtensions.Wpd)]
    [InlineData(LlamaParseSupportedFileExtensions.Wps)]
    [InlineData(LlamaParseSupportedFileExtensions.Wpt)]
    [InlineData(LlamaParseSupportedFileExtensions.Wq1)]
    [InlineData(LlamaParseSupportedFileExtensions.Wq2)]
    [InlineData(LlamaParseSupportedFileExtensions.Wri)]
    [InlineData(LlamaParseSupportedFileExtensions.Xhtm)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlr)]
    [InlineData(LlamaParseSupportedFileExtensions.Xls)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlsb)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlsm)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlsx)]
    [InlineData(LlamaParseSupportedFileExtensions.Xlw)]
    [InlineData(LlamaParseSupportedFileExtensions.Xml)]
    [InlineData(LlamaParseSupportedFileExtensions.Yxmd)]
    [InlineData(LlamaParseSupportedFileExtensions.Zabw)]
    public void SerializationRoundtrip_Works(LlamaParseSupportedFileExtensions rawValue)
    {
        // force implicit conversion because Theory can't do that for us
        ApiEnum<string, LlamaParseSupportedFileExtensions> value = rawValue;

        string json = JsonSerializer.Serialize(value, ModelBase.SerializerOptions);
        var deserialized = JsonSerializer.Deserialize<
            ApiEnum<string, LlamaParseSupportedFileExtensions>
        >(json, ModelBase.SerializerOptions);

        Assert.Equal(value, deserialized);
    }

    [Fact]
    public void InvalidEnumSerializationRoundtrip_Works()
    {
        var value = JsonSerializer.Deserialize<ApiEnum<string, LlamaParseSupportedFileExtensions>>(
            JsonSerializer.SerializeToElement("invalid value"),
            ModelBase.SerializerOptions
        );
        string json = JsonSerializer.Serialize(value, ModelBase.SerializerOptions);
        var deserialized = JsonSerializer.Deserialize<
            ApiEnum<string, LlamaParseSupportedFileExtensions>
        >(json, ModelBase.SerializerOptions);

        Assert.Equal(value, deserialized);
    }
}
